# Generated by Django 6.0.3 on 2026-03-19 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apka', '0003_alter_vote_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='votingsession',
            name='count_of_votes',
        ),
    ]
